name: UpdateTODO

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *' 
  workflow_dispatch:       # Allows manual triggering from the Actions tab

# on:
#   [push]


jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run check of pwd
      run: pwd
    - name: Run check of what's in pwd
      run: ls
    - name: Run a one-line script
      run: python ./.github/workflows/todo_List.py
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
    
      
      
